### ISSUE TITLE
u suck

### ISSUE THREAD

**Issue by Gumeez** [ChoqRe1/Java-Apps#1]
pls fix this

**Comment by Gumeez** [comment]
may require research team

**Comment by Gumeez** [comment]
`if(retarded)
        remi.suicide(); `

**Comment by ChoqRe1** [comment]
>##  I didn't want to wake up. I was having a much better time asleep. And that's really sad. It was almost like a reverse nightmare, like when you wake up from a nightmare you're so relieved. I woke up into a nightmare.
-**Ned Vizzini, It's Kind of a Funny Story**

@Gumeez if you think that these comments are appropriate you are wrong, this is a professional/student page. Please, those types of comments are reserved for [Facebook Comments](https://www.facebook.com/groups/1794108097469535/). I would appreciate it if you would refrain from posting any other comments of this type. 

#P.-S. Here is the code for the html table
`<table>
  <tr>
    <th rowspan="2">Just Java</th>
    <th>Regular house blend, decaffeinated coffee, or flavour of the day. </th>
  </tr>
  <tr>
    <td>Endless Cup $2.00</td>
  </tr>
  <tr>
    <td rowspan="2">Cafe au Lait</td>
    <td>House blended coffee infused into a smooth, steamed milk.</td>
  </tr>
  <tr>
    <td>Single $2.00 Double $4.00</td>
  </tr>
  <tr>
    <td rowspan="2">Iced Cappuccino</td>
    <td>Sweetened espresso blended with icy-cold milk and served in a chilled glass.</td>
  </tr>
  <tr>
    <td>Single $4.75 Double $5.75</td>
  </tr>
</table>`
